apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: fluent-bit
  namespace: fleet-default
spec:
  repo: https://github.com/aymanlinuxBoy/node-api.git
  branch: main
  paths:
    - fleet/fluent-bit
  # Uncomment and fill in if the repo is private:
  # clientSecretName: git-auth-secret
  targets:
    - name: downstream
      clusterSelector:
        matchLabels:
          env: downstream

