apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: metallb
  namespace: fleet-default
spec:
  repo: https://github.com/aymanlinuxBoy/node-api.git
  branch: main
  paths:
    - fleet/metallb
  targets:
    - name: downstream
      clusterSelector:
        matchLabels:
          env: downstream
