apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: node-api-poc-bg-success-rate
  namespace: devsecops-bg
spec:
  metrics:
    - name: prometheus-up
      interval: 10s
      count: 3
      successCondition: result[0] > 0
      failureLimit: 1
      provider:
        prometheus:
          # NOTE: adjust to your cluster's Prometheus service address.
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(up{job="node-api-poc-bg"})
